-- DROP DATABASE IF EXISTS test;

CREATE DATABASE IF NOT EXISTS test;

USE test;

CREATE TABLE IF NOT EXISTS phonelist(
    id INT NOT NULL AUTO_INCREMENT,
    fname NVARCHAR(255) NOT NULL,
    lname NVARCHAR(255) NOT NULL,
    phone NVARCHAR(11) NOT NULL,
    bday DATE NOT NULL,
    PRIMARY KEY(id)
);
